name: travelapps
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - lib/assets/images/lw.jpg
    - lib/assets/images/spk.jpg
    - lib/assets/images/majt.jpg
    - lib/assets/images/bc.jpg
    - lib/assets/images/kl.jpg
    - lib/assets/images/pwg.jpg
    - lib/assets/images/kmg.jpg
    - lib/assets/images/akg.jpg
    - lib/assets/images/mg.jpg
    - lib/assets/images/user.png
